apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
    name: $CatSourceName
    namespace: openshift-marketplace
    annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
spec:
    displayName: $displayName
    image: $imageUrl
    publisher: Red Hat
    sourceType: grpc
    updateStrategy:
      registryPoll:
        interval: 30m
