kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-storage
  namespace: openshift-image-registry
  annotations:
    volume.beta.kubernetes.io/storage-class: fs-lso 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
