apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: mc-dummy 
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents: $contents
        filesystem: $user 
        mode: $perms
        path: $path 

